# -*- coding: utf-8 -*-
"""DB_scan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdBP3WHzduZt88xtE7Z3fMsdwZyn2XpT
"""

import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Wholesale customers data.csv")

df

df.isnull().sum()

X = df.drop(['Channel', 'Region'], axis=1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

dbscan = DBSCAN(eps=0.5, min_samples=5)
clusters = dbscan.fit_predict(X_scaled)

df['Cluster'] = clusters

labels = dbscan.labels_
n_clusters = len(set(labels)) - (1 if -1 in labels else 0)
print(f'Number of clusters formed: {n_clusters}')

if n_clusters > 1:
    score = silhouette_score(X_scaled, labels)
    print(f'Silhouette Score: {score:.4f}')
else:
    print('Silhouette Score cannot be calculated (1 or fewer clusters found).')

print(pd.Series(labels).value_counts())

