# -*- coding: utf-8 -*-
"""L1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fz8ZhweQcjo1uFDUPIvrk-U5KFwen5pN
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

import warnings
warnings.filterwarnings('ignore')

dataset = pd.read_csv('./mtcars.csv')

dataset.head()

dataset.nunique()

dataset.isnull().sum()

dataset.shape

X = dataset.drop(['mpg', 'model'], axis=1)
y = dataset['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
reg.fit(X_train, y_train)

reg.score(X_test, y_test)

reg.score(X_train, y_train)

lasso_reg = Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(X_train, y_train)

lasso_reg.score(X_test, y_test)

lasso_reg.score(X_train, y_train)

ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(X_train, y_train)

ridge_reg.score(X_test, y_test)

ridge_reg.score(X_train, y_train)