# -*- coding: utf-8 -*-
"""Logistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181qczRACBeDXb0c4TzaUeOBqI4-iBiBl
"""

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_csv("HR_comma_sep.csv")
df.head()

df.info()

plt.figure(figsize=(10, 6))
sns.barplot(x='Department', y='left', data=df)
plt.title('Employee Retention by Department')
plt.xlabel('Department')
plt.ylabel('Retention Rate')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.barplot(x='salary', y='left', data=df, order=['low', 'medium', 'high'])
plt.title('Employee Retention by Salary Level')
plt.xlabel('Salary Level')
plt.ylabel('Retention Rate')
plt.tight_layout()
plt.show()

X = df.drop(['left'], axis=1)
y = df['left']

X_encoded = pd.get_dummies(X, columns=['Department', 'salary'], drop_first=True)
display(X_encoded.head())

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

X_test

y_predicted = model.predict(X_test)

model.score(X_test,y_test)

model.coef_

model.intercept_

pred =
prediction_function(pred)