# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFJ0jK1DdrvKAV91xhrHVXlx2dsbGAn8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Student_Performance.csv")

df

df.info()

df['gender'] = df['gender'].map({'male': 1, 'female': 2, 'other': 3})
df['school_type'] = df['school_type'].map({'public': 1, 'private': 2})
df['internet_access'] = df['internet_access'].map({'yes': 1, 'no': 0})
df['extra_activities'] = df['extra_activities'].map({'yes': 1, 'no': 0})
df['parent_education'] = df['parent_education'].map({'no formal': 0,'high school': 1,'diploma': 2,'graduate': 3,'post graduate': 4,'phd': 5})
df['travel_time'] = df['travel_time'].map({'<15 min': 0,'15-30 min': 1,'30-60 min': 2,'>60 min': 3})
df['study_method'] = df['study_method'].map({'notes': 0,'textbook': 1,'group study': 2,'mixed': 3,'coaching': 4})

def calculate_grade(score):
    if score >= 70:
        return '1'
    elif score >= 40:
        return '2'
    else:
        return '3'

df['calculated_grade'] = df['overall_score'].apply(calculate_grade)

df = df.drop("final_grade",axis =1)
df = df.drop("study_method",axis =1)

df

df.isnull().sum()

X = df.drop(['calculated_grade'], axis=1)
y = df['calculated_grade']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

svr_model = SVR(kernel='rbf')

non_numeric_cols = X_train.select_dtypes(include=['object']).columns
for col in non_numeric_cols:
    X_train[col] = pd.to_numeric(X_train[col], errors='coerce')

X_train_cleaned = X_train.fillna(-1)

svr_model.fit(X_train_cleaned, y_train)

y_pred = svr_model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared: {r2:.4f}")

plt.figure(figsize=(8,6))
colors = {'1': 'green','2': 'blue','3': 'red'}
grade_labels = {'1': 'Level A','2': 'Level B','3': 'Level C'}
for grade_numeric, color in colors.items():
    subset = df[df["calculated_grade"] == grade_numeric]
    plt.scatter(subset["math_score"], subset["overall_score"], color=color,label=grade_labels[grade_numeric],s=50)


input_overall_score = 70.0
student_level = calculate_grade(input_overall_score)

plt.scatter(
    input_overall_score,
    input_overall_score,
    color=colors[student_level],
    marker='X',
    s=300,
    edgecolor='black',
    linewidth=2,
    label=f'Input Student (Level {student_level})'
)

plt.title("Student Classification using SVM")
plt.xlabel("Math Score")
plt.ylabel("Overall Score")
plt.legend(title="Levels")
plt.grid(True)
plt.xlim(0,100)
plt.ylim(0,100)

plt.show()

input_overall_score = 70.0

student_level = calculate_grade(input_overall_score)

print(f"For an overall score of {input_overall_score}, the student's level is: {student_level}")