# -*- coding: utf-8 -*-
"""XG_Boost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KFFI-L6axYpcGOKA6OGeVSMeNGW2rjF
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix,accuracy_score

df = pd.read_csv("/content/Churn-Modelling.csv")
df

x = df.iloc[:,3:13].values
y = df.iloc[:,13].values

label_x = LabelEncoder()
x[:,1] = label_x.fit_transform(x[:,1])
x[:,2] = label_x.fit_transform(x[:,2])

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

classifier = XGBClassifier()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

x

y_pred

len(X_train)

